export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CURRENCY_NOT_ACTIVE: 'CURRENCY_NOT_ACTIVE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;

export const HttpStatus = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  TOKEN_EXPIRED: 401,
  PAYMENT_FAILED: 402,
  CURRENCY_NOT_ACTIVE: 400,
  INTERNAL_ERROR: 500,
  RATE_LIMIT_EXCEEDED: 429,
} as const;
