import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { firms, firmUsers, roles, reminders } from "@/lib/schema";
import { nanoid } from "nanoid";
import { getAccessToken, verifyToken, AccessTokenPayload, setAccessCookie, signAccessToken } from "@/lib/auth";
import { PermissionKeys } from "@/lib/rbac/permissions";

export async function POST(request: NextRequest) {
  try {
    const token = await getAccessToken();
    if (!token) return NextResponse.json({ message: "غير مصرح" }, { status: 401 });
    const payload = verifyToken<AccessTokenPayload>(token);

    const body = await request.json();
    const {
      name,
      logoUrl,
      primaryColor,
      secondaryColor,
      timezone,
      address,
      phone,
      email,
      licenseNumber,
      tag,
      
    } = body as {
      name: string;
      logoUrl?: string;
      primaryColor?: string;
      secondaryColor?: string;
      timezone?: string;
      address?: string;
      phone?: string;
      email?: string;
      licenseNumber?: string;
      tag?: string;
      licenseDocumentUrl?: string;
      licenseExpiryDate?: string;
    };

    if (!name || !name.trim()) {
      return NextResponse.json({ message: "الاسم مطلوب" }, { status: 400 });
    }

    const firmId = nanoid();

    const newFirm = {
      id: firmId,
      name: name.trim(),
      logoUrl: logoUrl || null,
      primaryColor: primaryColor || undefined,
      secondaryColor: secondaryColor || undefined,
      timezone: timezone || undefined,
      address: address || null,
      phone: phone || null,
      email: email || null,
      licenseNumber: licenseNumber || null,
      tag: tag || null,
      adminId: payload.userId,
      settings: {
        licenseDocumentUrl: body.licenseDocumentUrl || null,
        licenseExpiryDate: body.licenseExpiryDate || null,
        currency: body.currency || null,
      }
    } as Partial<typeof firms.$inferInsert>;

    const [createdFirm] = await db.insert(firms).values(newFirm as typeof firms.$inferInsert).returning();

    const adminRoleId = nanoid();
    const allPerms = Object.values(PermissionKeys);
    await db.insert(roles).values({
      id: adminRoleId,
      firmId,
      name: "admin",
      description: "Full access",
      permissions: allPerms,
    });

    await db.insert(firmUsers).values({
      id: nanoid(),
      firmId,
      userId: payload.userId,
      roleId: adminRoleId,
      status: "active",
    });

    const newAccess = signAccessToken({ userId: payload.userId, role: "admin", firmId, firmName: createdFirm.name });
    await setAccessCookie(newAccess);

    if (body.licenseExpiryDate) {
      const due = new Date(body.licenseExpiryDate);
      await db.insert(reminders).values({
        id: nanoid(),
        firmId,
        reminderType: "document_expiry",
        relatedEntityType: null as unknown as undefined,
        relatedEntityId: null,
        title: "Firm license expiry",
        message: `Firm license expires on ${due.toISOString()}`,
        dueDate: due,
        status: "active",
        priority: "high",
        isAutoGenerated: true,
        metadata: { licenseNumber: licenseNumber || null, licenseDocumentUrl: body.licenseDocumentUrl || null },
        createdBy: payload.userId,
      });
    }

    return NextResponse.json({ firm: createdFirm }, { status: 201 });
  } catch {
    return NextResponse.json({ message: "حدث خطأ" }, { status: 500 });
  }
}
