/**
 * Reminders Table Schema
 * Automated and manual reminders for important dates and actions
 * Tracks judgment appeals, document expiries, and custom reminders
 */

import { pgTable, varchar, text, timestamp, boolean, jsonb, index } from "drizzle-orm/pg-core";
import { reminderTypeEnum, relatedEntityTypeEnum, reminderStatusEnum, priorityEnum } from "../enums";

export const reminders = pgTable("reminders", {
  id: varchar("id", { length: 64 }).primaryKey(),
  firmId: varchar("firm_id", { length: 64 }).notNull(),
  reminderType: reminderTypeEnum("reminder_type").notNull(),
  relatedEntityType: relatedEntityTypeEnum("related_entity_type"),
  relatedEntityId: varchar("related_entity_id", { length: 64 }),
  scope: varchar("scope", { length: 20 }).default("personal").notNull(), // personal | firm
  title: varchar("title", { length: 500 }).notNull(),
  message: text("message").notNull(),
  dueDate: timestamp("due_date", { withTimezone: true }).notNull(),
  status: reminderStatusEnum("status").default("active").notNull(),
  snoozedUntil: timestamp("snoozed_until", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }), // Auto-dismiss after this date (e.g., 30 days for judgments)
  priority: priorityEnum("priority").default("medium").notNull(),
  isAutoGenerated: boolean("is_auto_generated").default(false).notNull(),
  assignedTo: jsonb("assigned_to"), // Stores array of user IDs or "all"
  metadata: jsonb("metadata"), // Store additional context (e.g., judgment date, document type)
  createdBy: varchar("created_by", { length: 64 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => ({
  firmIdx: index("reminders_firm_idx").on(table.firmId),
  typeIdx: index("reminders_type_idx").on(table.reminderType),
  statusIdx: index("reminders_status_idx").on(table.status),
  dueDateIdx: index("reminders_due_date_idx").on(table.dueDate),
  expiresIdx: index("reminders_expires_idx").on(table.expiresAt),
  scopeIdx: index("reminders_scope_idx").on(table.scope),
}));

export type Reminder = typeof reminders.$inferSelect;
export type InsertReminder = typeof reminders.$inferInsert;
